name: Build iOS Dylib

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Install Dependencies
        run: |
          xcode-select --install || true

      - name: Create iOS Framework
        run: |
          mkdir -p cpux_lib.framework/Headers
          cp cpux_lib.h cpux_lib.framework/Headers/
          clang -target arm64-apple-ios14.0 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -fPIC -c cpux_lib.c -o cpux_lib_ios.o
          libtool -static cpux_lib_ios.o -o cpux_lib.framework/cpux_lib
          mkdir -p cpux_lib.framework/Modules
          echo 'framework module cpux_lib { header "cpux_lib.h" export * }' > cpux_lib.framework/Modules/module.modulemap

      - name: Create iOS XCFramework
        run: |
          xcodebuild -create-xcframework -framework cpux_lib.framework -output cpux_lib.xcframework

      - name: Zip iOS Framework
        run: |
          zip -r cpux_lib.framework.zip cpux_lib.framework

      - name: Zip iOS XCFramework
        run: |
          zip -r cpux_lib.xcframework.zip cpux_lib.xcframework

      - name: Create iOS Dylib
        run: |
          clang -dynamiclib -target arm64-apple-ios14.0 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -o libcpux.dylib cpux_lib_ios.o -framework Foundation

  release:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Install Dependencies
        run: |
          xcode-select --install || true

      - name: Create iOS Framework
        run: |
          mkdir -p cpux_lib.framework/Headers
          cp cpux_lib.h cpux_lib.framework/Headers/
          clang -target arm64-apple-ios14.0 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -fPIC -c cpux_lib.c -o cpux_lib_ios.o
          libtool -static cpux_lib_ios.o -o cpux_lib.framework/cpux_lib
          mkdir -p cpux_lib.framework/Modules
          echo 'framework module cpux_lib { header "cpux_lib.h" export * }' > cpux_lib.framework/Modules/module.modulemap

      - name: Create iOS XCFramework
        run: |
          xcodebuild -create-xcframework -framework cpux_lib.framework -output cpux_lib.xcframework

      - name: Zip iOS Framework
        run: |
          zip -r cpux_lib.framework.zip cpux_lib.framework

      - name: Zip iOS XCFramework
        run: |
          zip -r cpux_lib.xcframework.zip cpux_lib.xcframework

      - name: Create iOS Dylib
        run: |
          clang -dynamiclib -target arm64-apple-ios14.0 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -o libcpux.dylib cpux_lib_ios.o -framework Foundation

      - name: Delete Existing Release and Tag
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
        run: |
          gh release delete Dylib -y
          git push --delete origin Dylib || true

      - name: Create Release and Set Tag
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
        run: |
          git tag Dylib
          git push origin Dylib
          gh release create Dylib cpux_lib.framework.zip cpux_lib.xcframework.zip libcpux.dylib --title "Dylib Release" --notes "Release notes for Dylib"