name: Create New Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest # Use macos-latest for the latest Xcode

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable' # Or a specific version that supports the latest swift

      - name: Clean build environment
        run: |
          rm -rf build upload
          mkdir -p build upload

      - name: Install dependencies (packages)
        run: |
          brew update
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip gnu-sed

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: /Users/runner/Library/Caches/Homebrew
          key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Brewfile.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-homebrew-

      - name: Compile
        run: |
          make package SCHEME="'feather (Release)'" OPTIMIZATION_LEVEL=-Onone
          mv packages/* upload/

      - name: Get Version Number
        id: get_version
        run: |
          VERSION=$( /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/backdoor.app/Info.plist )
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Setup
        run: |
          mv upload/backdoor.ipa upload/backdoor_v${VERSION}.ipa
          cp upload/backdoor_v${VERSION}.ipa upload/backdoor_v${VERSION}.tipa

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Backdoor v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/*ipa
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Notify Build Success
        if: success()
        run: echo "Build and release process completed successfully."

      - name: Notify Build Failure
        if: failure()
        continue-on-error: true
        run: echo "Build and release process failed."

  retrieve_logs:
    needs: build
    runs-on: ubuntu-latest
    if: always() # This job will run regardless of the previous job's outcome
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Retrieve Workflow Logs
        continue-on-error: true
        run: |
          # Fetch the workflow run information first to get logs_url
          RUN_INFO=$(curl -s -H "Authorization: token ${{ secrets.WORKFLOW_SECRET }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}")
          
          # Extract logs_url from the run info
          LOGS_URL=$(echo $RUN_INFO | jq -r '.logs_url')
          
          if [ -n "$LOGS_URL" ]; then
            # Download logs if logs_url is available
            curl -s -H "Authorization: token ${{ secrets.WORKFLOW_SECRET }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "$LOGS_URL" -o logs.zip
            mkdir -p logs
            unzip -o logs.zip -d logs/
          else
            echo "No logs URL found for this run."
          fi
        shell: bash

      - name: Save Logs
        run: |
          mkdir -p Logs
          cp -r logs/*.log Logs/ || echo "No logs to copy"

      - name: Commit and Push Logs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Logs/*.log
          git commit -m "Add workflow logs" || echo "No changes to commit"
          git push origin main